import { useState } from 'react';
import { Upload, FileText, ExternalLink, Trash2, LockKeyhole, Check, X } from 'lucide-react';
import type { Action, Configuration, Submission } from '../types';
import { uploadPdf, download } from '../services/api';
import { Card, StatusBadge, EmptyState } from './ui';
import { Modal } from './Modal';
export function DocumentUpload({submission,config,editable,busy,action,onChange,onError,setBusy}:{submission:Submission;config:Configuration;editable:boolean;busy:boolean;action:Action;onChange:(s:Submission)=>void;onError:(e:unknown)=>void;setBusy:(s:string)=>void}){
  const [type,setType]=useState(config.required_documents[0]);const [stage,setStage]=useState('');const [preview,setPreview]=useState<{url:string;name:string}|null>(null);
  const docs=submission.documents.filter(d=>d.is_current);const complete=config.required_documents.filter(t=>docs.some(d=>d.type===t)).length;
  async function upload(files:FileList|null){if(!files)return;setBusy('Mengunggah dokumen');let current=submission;try{for(const file of Array.from(files)){setStage(`Mengunggah ${file.name}…`);const body=new FormData();body.append('file',file);body.append('type',type);body.append('data_version',String(current.data_version));current=await uploadPdf<Submission>(`/submissions/${submission.id}/documents`,body,(percent,transferred)=>{setStage(transferred?'Unggahan terkirim. Menunggu hasil ekstraksi…':`Mengunggah${percent!==null?' '+percent+'%':''}…`);});onChange(current);}}catch(e){onError(e);}finally{setStage('');setBusy('');}}
  async function open(id:number,name:string){try{setPreview({url:await download(submission.id,id),name});}catch(e){onError(e);}}
  return <Card title="Dokumen pendukung" eyebrow="02 / LAMPIRAN PENGAJUAN" id="documents" aside={<span className="count-pill">{complete}/{config.required_documents.length} lengkap</span>}>
    <div className="requirement-list">{config.required_documents.map(t=><span key={t} className={docs.some(d=>d.type===t)?'complete':''}><Check size={12}/>{config.documents[t]}</span>)}</div>
    {editable&&<><label className="upload-type">Jenis dokumen<select value={type} disabled={busy} onChange={e=>setType(e.target.value)}>{Object.entries(config.documents).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className={`upload-zone ${busy?'disabled':''}`}><input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value='';}}/><span className="upload-icon"><Upload size={20}/></span><strong>{stage||'Pilih PDF untuk diunggah'}</strong><span>PDF hingga {config.max_upload_kb/1024} MiB per berkas</span><small>Jenis yang sama akan menggantikan versi aktif.</small></label></>}
    {docs.length===0?<EmptyState>Belum ada dokumen. Mulai dengan salah satu lampiran di atas.</EmptyState>:<div className="document-list">{docs.map(d=><div className="document-card" key={d.id}><span className="file-icon"><FileText size={21}/><small>PDF</small></span><div className="document-info"><strong>{d.original_filename}</strong><span>{config.documents[d.type]} · versi {d.version}</span><StatusBadge status={d.extraction_status}/>{d.extraction_status!=='ready'&&<p>{d.extraction_metadata.message}</p>}</div><div className="document-actions"><button className="icon-button" title="Pratinjau PDF" aria-label={`Buka ${d.original_filename}`} onClick={()=>void open(d.id,d.original_filename)}><ExternalLink size={16}/></button>{editable&&<button className="icon-button" title="Hapus dari dokumen aktif" aria-label={`Hapus ${d.original_filename}`} disabled={busy} onClick={()=>void action(`/documents/${d.id}`,{},'DELETE')}><Trash2 size={15}/></button>}</div></div>)}</div>}
    <p className="privacy-note"><LockKeyhole size={12}/> Dokumen privat, hanya untuk kamu dan peninjau.</p>
    {submission.documents.some(d=>!d.is_current)&&<details className="history"><summary>Riwayat dokumen sebelumnya</summary>{submission.documents.filter(d=>!d.is_current).map(d=><button key={d.id} className="history-document" onClick={()=>void open(d.id,d.original_filename)}>{d.original_filename} · versi {d.version}<ExternalLink size={13}/></button>)}</details>}
    {preview&&<Modal className="pdf-modal" label="Pratinjau dokumen" onClose={()=>{URL.revokeObjectURL(preview.url);setPreview(null);}}><header><strong>{preview.name}</strong><button autoFocus className="icon-button" aria-label="Tutup pratinjau" onClick={()=>{URL.revokeObjectURL(preview.url);setPreview(null);}}><X size={20}/></button></header><iframe title={preview.name} src={preview.url}/><a href={preview.url} download={preview.name}>Unduh PDF</a></Modal>}
  </Card>;
}
