import { useState } from 'react';
import { ScanLine, ArrowRight, ExternalLink, ShieldCheck, AlertCircle } from 'lucide-react';
import type { Action, Finding, Submission } from '../types';
import { Card, StatusBadge, LoadingButton, EmptyState } from './ui';
import { download } from '../services/api';
export function FindingCard({finding,submission,onError}:{finding:Finding;submission:Submission;onError:(e:unknown)=>void}){
  const doc=submission.documents.find(d=>d.is_current&&(d.id===finding.document_id||d.original_filename===finding.document));
  return <article className={`finding ${finding.severity}`}><div className="finding-title"><AlertCircle size={16}/><strong>{finding.issue}</strong></div><div className="finding-meta"><span>{finding.field||'Dokumen'}</span><span>{finding.rule}</span><span>{finding.source==='ai'?'Analisis AI':'Pemeriksaan sistem'}</span></div>{finding.evidence&&<blockquote>{finding.evidence}{finding.evidence_verified===false&&<small>Kutipan belum dapat diverifikasi otomatis.</small>}</blockquote>}<p>{finding.suggested_action}</p>{doc?<button className="text-button" onClick={async()=>{const win=window.open('','_blank');try{const url=await download(submission.id,doc.id);if(win){win.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch(e){win?.close();onError(e);}}}><ExternalLink size={13}/>{doc.original_filename}{finding.page?` · hal. ${finding.page}`:''}</button>:finding.document&&<small>{finding.document}</small>}</article>;
}
export function PreCheckResult({submission,action,busy,editable,onError}:{submission:Submission;action:Action;busy:boolean;editable:boolean;onError:(e:unknown)=>void}){
  const [human,setHuman]=useState(false);const current=submission.prechecks.find(p=>!p.is_stale&&p.status==='COMPLETED');const latest=submission.prechecks[0];
  const requiresHuman=!current||current.result?.status==='NEEDS_HUMAN_CHECK';const canSubmit=editable&&!submission.completeness.findings.length&&current?.result?.status!=='NEEDS_FIX'&&(!requiresHuman||human);
  return <Card title="Pemeriksaan awal" eyebrow="03 / TINJAU SEBELUM MENGIRIM" id="precheck" aside={<ScanLine size={20} className="muted"/>}>
    <p className="section-description">Periksa kelengkapan dan kecocokan data antardokumen sebelum pengajuan ditinjau.</p>
    {current?.result?<><div className="precheck-summary"><StatusBadge status={current.result.status}/><span>{current.result.findings.length} temuan</span></div><p className="summary-text">{current.result.summary}</p>{current.result.findings.map((f,i)=><FindingCard key={i} finding={f} submission={submission} onError={onError}/>)}<details className="human-checks"><summary><ShieldCheck size={15}/> Pemeriksaan manusia ({current.result.human_checks.length})</summary>{current.result.human_checks.map((f,i)=><FindingCard key={i} finding={f} submission={submission} onError={onError}/>)}</details></>:<EmptyState><ScanLine size={25}/><strong>{latest?.is_stale?'Dokumen atau data telah berubah':'Belum diperiksa'}</strong><span>{latest?.is_stale?'Jalankan pemeriksaan baru untuk versi saat ini.':'Lengkapi data dan unggah PDF untuk memulai.'}</span></EmptyState>}
    {latest?.status==='FAILED'&&<p className="inline-warning">Analisis terakhir tidak selesai. Gangguan layanan bukan temuan administratif.</p>}
    {submission.completeness.findings.length>0&&<details className="history"><summary>{submission.completeness.findings.length} kelengkapan yang masih perlu disiapkan</summary>{submission.completeness.findings.map((f,i)=><p key={i}>{f.issue}</p>)}</details>}
    {editable&&<><LoadingButton className="button secondary full" busy={busy} onClick={()=>void action('/precheck')}><ScanLine size={16}/>Jalankan pemeriksaan{current?' ulang':''}</LoadingButton><div className="submit-section">{requiresHuman&&<label className="checkbox-label"><input type="checkbox" checked={human} onChange={e=>setHuman(e.target.checked)}/>Saya memahami analisis belum tuntas dan meminta peninjau memeriksa berkas secara manual.</label>}<LoadingButton className="button primary full" busy={busy} disabled={!canSubmit} onClick={()=>void action(submission.status==='REVISION_REQUESTED'?'/resubmit':'/submit',{human_review:human})}>{submission.status==='REVISION_REQUESTED'?'Kirim ulang pengajuan':'Kirim pengajuan'}<ArrowRight size={16}/></LoadingButton><p className="footnote">Pengajuan dikirim hanya setelah kamu menekan tombol ini. Lulus pemeriksaan bukan berarti disetujui.</p></div></>}
    {submission.prechecks.length>0&&<details className="history"><summary>Riwayat pemeriksaan ({submission.prechecks.length})</summary>{submission.prechecks.map(p=><details key={p.id}><summary>Versi {p.data_version} · {p.is_stale?'Bukti lama':p.result?.status||p.status}</summary>{p.result?<><p>{p.result.summary}</p>{p.result.findings.map((f,i)=><p key={i}>{f.issue} — {f.document}</p>)}</>:<p>Analisis tidak selesai ({p.error_code}).</p>}</details>)}</details>}
  </Card>;
}
