import { useState } from 'react';
import { ShieldCheck, Sparkles } from 'lucide-react';
import type { Action, Submission } from '../types';
import { Card, EmptyState, LoadingButton, StatusBadge } from './ui';
export function ReviewerView({submission,action,busy}:{submission:Submission;action:Action;busy:boolean}){
  const [comment,setComment]=useState('');const [decision,setDecision]=useState('REVISION_REQUESTED');const summary=submission.summaries.find(s=>!s.is_stale);const active=['SUBMITTED','UNDER_REVIEW'].includes(submission.status);
  return <div className="reviewer-panel"><Card title="Ringkasan peninjau" eyebrow="BANTUAN AI UNTUK PENINJAU" aside={<Sparkles size={20}/>}>{summary?<><p className="summary-text">{summary.result.review_summary}</p><ul className="key-facts">{summary.result.key_facts.map((f,i)=><li key={i}>{f.fact}<small>{f.source_document||'Data formulir'}{f.page?` · halaman ${f.page}`:''}{!f.source_verified?' · sumber perlu diverifikasi':''}</small></li>)}</ul></>:<EmptyState>Ringkasan belum tersedia untuk bukti saat ini.</EmptyState>}<LoadingButton className="button secondary full" busy={busy} onClick={()=>void action('/reviewer-summary')}><Sparkles size={16}/>Buat ringkasan AI</LoadingButton><p className="footnote">Ringkasan adalah saran. Periksa PDF asli dan bukti sebelum memutuskan.</p></Card>
    <Card title="Keputusan pengajuan" eyebrow="OTORITAS PENINJAU" aside={<ShieldCheck size={20}/>}>{active?<form onSubmit={e=>{e.preventDefault();void action('/review',{decision,comment});}}><label>Keputusan<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="REVISION_REQUESTED">Minta revisi</option><option value="APPROVED">Setujui pengajuan</option><option value="REJECTED">Tolak pengajuan</option></select></label><label>Catatan untuk mahasiswa<textarea rows={5} minLength={10} maxLength={4000} required value={comment} onChange={e=>setComment(e.target.value)} placeholder="Jelaskan dokumen, nilai yang perlu diperbaiki, dan langkah berikutnya…"/></label><LoadingButton className="button primary full" type="submit" busy={busy} disabled={comment.trim().length<10}>Simpan keputusan</LoadingButton></form>:<><StatusBadge status={submission.status}/><p className="section-description">Keputusan tersedia ketika pengajuan dikirim untuk ditinjau.</p></>}{submission.reviews.map(r=><div className="review-feedback" key={r.id}><StatusBadge status={r.decision}/><p>{r.comment}</p><small>Bukti versi {r.data_version} · {new Date(r.created_at).toLocaleDateString('id-ID')}</small></div>)}</Card>
  </div>;
}
