import { useState } from 'react';
import { ArrowRight, RotateCcw, Check } from 'lucide-react';
import type { Action, Configuration, Plan, Submission } from '../types';
import { Card, LoadingButton, date } from './ui';
function CorrectionComparison({plan,config,action,busy}:{plan:Plan;config:Configuration;action:Action;busy:boolean}){
  const [selected,setSelected]=useState<string[]>([]);const active=!plan.is_stale&&plan.status==='PROPOSED';
  return <div className={`revision-plan ${!active?'inactive':''}`}><div className="plan-header"><strong>{plan.source==='chat'?'Konfirmasi informasi':'Rencana perbaikan'}</strong><span>Versi {plan.data_version}{plan.is_stale?' · Bukti lama':plan.status!=='PROPOSED'?' · Sudah diproses':''}</span></div><p>{plan.proposal.root_cause}</p>{plan.proposal.affected_fields.map(c=><div className="correction" key={c.field}><label className="checkbox-label"><input type="checkbox" disabled={!active||!c.selectable||busy} checked={selected.includes(c.field)} onChange={e=>setSelected(e.target.checked?[...selected,c.field]:selected.filter(f=>f!==c.field))}/><strong>{config.fields[c.field]||c.field}</strong></label><div className="comparison"><span>{date(c.current_value)}</span><ArrowRight size={15}/><strong>{date(c.proposed_value)}</strong></div><p>{c.reason}</p>{c.evidence&&<blockquote>{c.evidence}<small>{c.evidence_source}</small></blockquote>}<small>{c.external_action}</small>{!c.selectable&&<p className="inline-warning">Sumber belum terverifikasi. Periksa dokumen dan edit informasi secara manual.</p>}</div>)}{plan.proposal.recommended_changes.length>0&&<ol>{plan.proposal.recommended_changes.map((c,i)=><li key={i}>{c}</li>)}</ol>}{active&&<div className="button-row"><LoadingButton className="button primary" busy={busy} disabled={!selected.length} onClick={()=>void action(`/revision-plans/${plan.id}/apply`,{selected_fields:selected})}><Check size={15}/>Terima {selected.length} koreksi</LoadingButton><button className="button secondary" disabled={busy} onClick={()=>void action(`/revision-plans/${plan.id}/apply`,{selected_fields:[]})}>Tolak usulan</button></div>}</div>;
}
export function RevisionPanel({submission,config,action,busy}:{submission:Submission;config:Configuration;action:Action;busy:boolean}){
  if(submission.status!=='REVISION_REQUESTED'&&!submission.plans.length)return null;
  return <Card title="Langkah perbaikan" eyebrow="REVISI & KONFIRMASI" id="revision" aside={<RotateCcw size={19} className="muted"/>}>{submission.status==='REVISION_REQUESTED'&&<><div className="review-feedback"><strong>Catatan peninjau</strong><p>{submission.reviews[0]?.comment}</p></div><p className="section-description">Unggah bukti pengganti yang relevan, lalu susun rencana. Pilih koreksi yang kamu setujui. Dokumen PDF tetap perlu diperbarui secara terpisah.</p><LoadingButton busy={busy} className="button secondary full" onClick={()=>void action('/revision-plan')}><RotateCcw size={16}/>Susun rencana perbaikan</LoadingButton></>}{submission.plans.map(p=><CorrectionComparison key={p.id} plan={p} config={config} action={action} busy={busy}/>)}</Card>;
}
