import { useEffect, useState } from 'react';
import { Check, ChevronDown, ClipboardList } from 'lucide-react';
import type { Action, Configuration, Fields, Submission } from '../types';
import { Card, LoadingButton, date } from './ui';
export function SubmissionFields({submission,config,action,busy,editable}:{submission:Submission;config:Configuration;action:Action;busy:boolean;editable:boolean}){
  const [fields,setFields]=useState<Fields>(submission.form_data);const [open,setOpen]=useState(false);const [demo,setDemo]=useState('');const [saved,setSaved]=useState(false);
  useEffect(()=>{setFields(submission.form_data);},[submission.form_data]);
  const filled=config.required_fields.filter(k=>fields[k]!==null&&fields[k]!==undefined&&fields[k]!=='').length;
  return <Card title="Informasi pengajuan" eyebrow="01 / DATA DIRI & PENEMPATAN" id="information" aside={<ClipboardList size={19} className="muted"/>}>
    <div className="facts-grid"><div><span>Mahasiswa</span><strong>{submission.form_data.student_name||'Belum diisi'}</strong><small>{submission.form_data.nim||'NIM belum diisi'}</small></div><div><span>Perusahaan tujuan</span><strong>{submission.form_data.company_name||'Belum diisi'}</strong><small>{date(submission.form_data.start_date)} — {date(submission.form_data.end_date)}</small></div></div>
    <button className="disclosure" onClick={()=>setOpen(!open)} aria-expanded={open}>{editable?'Lengkapi / edit informasi':'Lihat informasi lengkap'}<span>{filled}/{config.required_fields.length} isian <ChevronDown size={16}/></span></button>
    {open&&<form className="fields-form" onSubmit={async e=>{e.preventDefault();setSaved(await action('',{form_data:fields},'PATCH')===true);}}><div className="form-grid">{Object.entries(config.fields).map(([key,label])=><label key={key}>{label}{config.required_fields.includes(key)&&<span className="required"> *</span>}<input disabled={!editable||busy} value={fields[key]??''} type={key.endsWith('_date')?'date':key==='semester'?'number':'text'} min={key==='semester'?1:undefined} max={key==='semester'?20:undefined} maxLength={200} placeholder={key==='academic_year'?'2026/2027':label} onChange={e=>{setSaved(false);setFields({...fields,[key]:e.target.value===''?null:key==='semester'?Number(e.target.value):e.target.value});}}/></label>)}</div>{editable&&<LoadingButton className="button primary" busy={busy} type="submit">{saved?<Check size={16}/>:null}Simpan informasi</LoadingButton>}</form>}
    {editable&&<details className="demo-details"><summary>Gunakan kasus demo sintetis</summary><p>Hanya mengisi formulir. Unggah PDF asli dan jalankan analisis untuk menguji kasus.</p><label className="sr-only" htmlFor="demo-case">Kasus demo</label><select id="demo-case" disabled={busy} value={demo} onChange={e=>setDemo(e.target.value)}><option value="">Pilih kasus dari paket uji…</option>{config.demo_cases.map(c=><option key={c.id} value={c.id}>{c.id} · {c.title}</option>)}</select>{demo&&<><ul>{Object.values(config.demo_cases.find(c=>c.id===demo)!.documents).map(p=><li key={p}>{p.split('/').at(-1)}</li>)}</ul><button type="button" disabled={busy} className="button secondary" onClick={()=>{setFields(config.demo_cases.find(c=>c.id===demo)!.form_data);setOpen(true);}}>Pratinjau data formulir</button><small>Klik “Simpan informasi” untuk mengonfirmasi.</small></>}</details>}
  </Card>;
}
