import { LoaderCircle, ArrowUpRight, Check } from 'lucide-react';
import type { ButtonHTMLAttributes, ReactNode } from 'react';
export const labels:Record<string,string>={DRAFT:'Draf pengajuan',SUBMITTED:'Terkirim',UNDER_REVIEW:'Dalam peninjauan',REVISION_REQUESTED:'Perlu revisi',APPROVED:'Disetujui',REJECTED:'Ditolak',PASS:'Pemeriksaan lulus',NEEDS_FIX:'Perlu perbaikan',NEEDS_HUMAN_CHECK:'Perlu pemeriksaan manusia',ready:'Teks terbaca',needs_review:'Perlu dibaca manual',failed:'Ekstraksi gagal',RUNNING:'Sedang dianalisis',FAILED:'Analisis gagal',COMPLETED:'Selesai'};
export function StatusBadge({status}:{status:string}){return <span className={`badge ${['PASS','APPROVED','ready'].includes(status)?'good':['NEEDS_FIX','REVISION_REQUESTED','failed','REJECTED'].includes(status)?'warn':''}`}><span className="status-dot"/>{labels[status]||status}</span>}
export function LoadingButton({busy,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{busy?:boolean}){return <button {...props} disabled={props.disabled||busy}>{busy&&<LoaderCircle size={16} className="spin"/>}{children}</button>}
export function Card({title,eyebrow,children,aside,id}:{title:string;eyebrow?:string;children:ReactNode;aside?:ReactNode;id?:string}){return <section className="card" id={id}><div className="card-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{aside}</div>{children}</section>}
export function EmptyState({children}:{children:ReactNode}){return <div className="empty-state">{children}</div>}
export function date(value:unknown){if(!value)return 'Belum diisi';const s=String(value);return /^\d{4}-\d{2}-\d{2}$/.test(s)?new Date(s+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}):s;}
export function Step({index,done,active,label}:{index:number;done:boolean;active:boolean;label:string}){return <div className={`step ${active?'active':''} ${done?'done':''}`}><span>{done?<Check size={13}/>:index}</span>{label}<ArrowUpRight size={13}/></div>}
