import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, ChevronDown, CircleHelp, FileCheck2, FolderOpen, LayoutGrid, LogOut, Plus, RefreshCw, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { Action, Configuration, Submission, SubmissionList, User } from './types';
import { api, ApiError, token } from './services/api';
import { ChatPanel } from './components/ChatPanel';
import { SubmissionFields } from './components/SubmissionFields';
import { DocumentUpload } from './components/DocumentUpload';
import { PreCheckResult } from './components/PreCheckResult';
import { RevisionPanel } from './components/RevisionPanel';
import { Modal } from './components/Modal';
import { ReviewerView } from './components/ReviewerView';
import { LoadingButton, StatusBadge, Step } from './components/ui';
export default function App(){
  const [user,setUser]=useState<User|null>(null),[config,setConfig]=useState<Configuration|null>(null),[submission,setSubmission]=useState<Submission|null>(null),[list,setList]=useState<SubmissionList[]>([]);
  const [busy,setBusy]=useState(''),[error,setError]=useState<ApiError|null>(null),[boot,setBoot]=useState(true),[sop,setSop]=useState(false),[tab,setTab]=useState('chat');
  const [email,setEmail]=useState('mahasiswa@flowfix.test'),[password,setPassword]=useState('FlowFix-demo-2026!');
  const report=useCallback((e:unknown)=>setError(e instanceof ApiError?e:new ApiError('Terjadi kesalahan. Coba lagi.','UNKNOWN')),[]);
  const refreshList=useCallback(async()=>{const data=await api<SubmissionList[]>('/submissions');setList(data);return data;},[]);
  const load=useCallback(async(id:number)=>setSubmission(await api<Submission>(`/submissions/${id}`)),[]);
  const initialize=useCallback(async()=>{const me=await api<User>('/me');setUser(me);setConfig(await api<Configuration>('/configuration'));const entries=await refreshList();if(entries.length)await load(entries[0].id);else if(me.role==='student')setSubmission(await api<Submission>('/submissions','POST',{}));},[refreshList,load]);
  useEffect(()=>{if(token())initialize().catch(e=>{sessionStorage.removeItem('flowfix_token');report(e);}).finally(()=>setBoot(false));else setBoot(false);},[initialize,report]);
  async function login(){setBusy('Masuk');setError(null);try{const result=await api<{user:User;token:string}>('/login','POST',{email,password});sessionStorage.setItem('flowfix_token',result.token);await initialize();}catch(e){report(e);}finally{setBusy('');}}
  async function logout(){setBusy('Keluar');try{await api('/logout','POST');sessionStorage.removeItem('flowfix_token');setUser(null);setSubmission(null);setList([]);}catch(e){report(e);}finally{setBusy('');}}
  const action:Action=async(path,body={},method='POST')=>{if(!submission||busy)return false;setBusy(path.includes('messages')?'Asisten sedang menjawab':path.includes('precheck')?'Menganalisis dokumen':'Memproses pengajuan');setError(null);try{setSubmission(await api<Submission>(`/submissions/${submission.id}${path}`,method,{...body,data_version:submission.data_version}));await refreshList();return true;}catch(e){report(e);await load(submission.id).catch(()=>{});return false;}finally{setBusy('');}};
  async function newSubmission(){setBusy('Membuat pengajuan');try{setSubmission(await api<Submission>('/submissions','POST',{}));await refreshList();}catch(e){report(e);}finally{setBusy('');}}
  function navigate(section:string){setTab('documents');setTimeout(()=>document.getElementById(section)?.scrollIntoView({behavior:'smooth',block:'start'}),60);}
  const editable=user?.role==='student'&&!!submission&&['DRAFT','REVISION_REQUESTED'].includes(submission.status);
  const errorBox=error&&<div className="error-banner" role="alert"><div><strong>{error.message}</strong>{Object.entries(error.fields).map(([k,v])=><p key={k}>{config?.fields[k.replace('form_data.','')]||k}: {v.join(' ')}</p>)}{config?.debug&&<small>{error.code} · {error.requestId}</small>}</div><button className="icon-button" onClick={()=>setError(null)} aria-label="Tutup pesan kesalahan"><X size={17}/></button></div>;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/" aria-label="FlowFix beranda"><span className="brand-mark"><FileCheck2 size={24}/></span><strong>FlowFix<span>RUANG ADMINISTRASI</span></strong></a><div className="workspace-label">WORKSPACE</div><div className="sidebar-nav"><button className="nav-item selected"><LayoutGrid size={18}/>Pengajuan magang<span className="nav-dot"/></button><button className="nav-item" onClick={()=>setSop(true)} disabled={!config}><BookOpen size={18}/>Panduan & persyaratan<ArrowUpRight size={14}/></button></div><div className="sidebar-note"><span className="note-icon"><Sparkles size={18}/></span><strong>Lebih siap.<br/>Lebih sedikit revisi.</strong><p>Siapkan pengajuan dengan panduan yang jelas, dari awal sampai selesai.</p><div className="note-line"/></div><div className="sidebar-bottom"><div className="simulation-pill">DEMO HACKATHON</div><p>SOP simulasi, bukan kebijakan resmi UNS/FATISDA.</p><button className="text-button" onClick={()=>setSop(true)} disabled={!config}><CircleHelp size={15}/>Tentang demo</button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{user?.role==='reviewer'?'Ruang peninjau':'Pengajuan magang'}</strong></div><div className="topbar-right"><span className="private-label"><ShieldCheck size={14}/>Ruang privat</span>{user&&<><div className="profile-avatar">{user.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><div className="profile-info"><strong>{user.name}</strong><span>{user.role==='reviewer'?'Peninjau':'Mahasiswa'}</span></div><button className="icon-button" disabled={!!busy} aria-label="Keluar dan ganti akun" title="Keluar / ganti akun" onClick={()=>void logout()}><LogOut size={17}/></button></>}</div></header>
    {boot?<div className="boot-state">Memuat ruang pengajuan…</div>:!user?<main className="login-layout"><div className="login-intro"><span className="eyebrow">SELAMAT DATANG DI FLOWFIX</span><h1>Pengajuan magang,<br/>lebih terarah.</h1><p>Mulai dari percakapan. Siapkan dokumen, periksa informasi, dan ikuti proses pengajuanmu dalam satu ruang.</p><div className="login-features"><span><Sparkles size={18}/>Asisten pengajuan</span><span><FileCheck2 size={18}/>Pemeriksaan dokumen</span><span><ShieldCheck size={18}/>Peninjauan manusia</span></div></div><form className="login-card" onSubmit={e=>{e.preventDefault();void login();}}><div className="assistant-icon"><FolderOpen size={24}/></div><h2>Masuk ke ruang pengajuan</h2><p>Gunakan akun demo lokal untuk mencoba alur.</p>{errorBox}<label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Kata sandi<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><LoadingButton className="button primary full" busy={!!busy} type="submit">Masuk sebagai {email.startsWith('peninjau')?'peninjau':'mahasiswa'}<ArrowRight size={17}/></LoadingButton><div className="demo-login"><span>Akun sintetis · khusus demo lokal</span><button type="button" className="text-button" onClick={()=>setEmail(email.startsWith('peninjau')?'mahasiswa@flowfix.test':'peninjau@flowfix.test')}>{email.startsWith('peninjau')?'Gunakan akun mahasiswa':'Masuk sebagai peninjau'}<ArrowUpRight size={13}/></button></div></form></main>:<main className="workspace"><div className="page-heading"><div><p className="eyebrow">{user.role==='reviewer'?'TINJAU DENGAN BUKTI':'LANGKAH KECIL, PENGAJUAN LEBIH SIAP'}</p><h1>{user.role==='reviewer'?'Ruang peninjau':'Pengajuan magang'}</h1><p>{user.role==='reviewer'?'Periksa fakta, baca dokumen, dan berikan keputusan.':'Siapkan semuanya di sini. FlowFix menemanimu sampai tuntas.'}</p></div><div className="page-actions">{submission&&<StatusBadge status={submission.status}/>}<button className="icon-button" title="Muat ulang" aria-label="Muat ulang pengajuan" disabled={!!busy} onClick={()=>void initialize().catch(report)}><RefreshCw size={17}/></button></div></div>{errorBox}
      <div className="submission-toolbar"><label><span className="sr-only">Pilih pengajuan</span><select disabled={!!busy} value={submission?.id||''} onChange={e=>void load(Number(e.target.value)).catch(report)}>{!list.length&&<option>Belum ada pengajuan</option>}{list.map(s=><option key={s.id} value={s.id}>FF-{String(s.id).padStart(4,'0')} · {s.form_data.student_name||'Pengajuan baru'} · {s.form_data.company_name||'Magang mandiri'}</option>)}</select><ChevronDown size={14}/></label>{user.role==='student'&&<button className="text-button" disabled={!!busy} onClick={()=>void newSubmission()}><Plus size={14}/>Pengajuan baru</button>}<span className="saved-label">{busy||`Tersimpan${submission?' · versi '+submission.data_version:''}`}</span></div>
      {submission&&config?<><div className="progress-strip"><Step index={1} done={Object.keys(submission.form_data).length>0} active={editable} label="Siapkan pengajuan"/><Step index={2} done={submission.prechecks.some(p=>!p.is_stale&&p.status==='COMPLETED')} active={editable&&submission.documents.some(d=>d.is_current)} label="Periksa dokumen"/><Step index={3} done={['SUBMITTED','APPROVED','REJECTED'].includes(submission.status)} active={['SUBMITTED','UNDER_REVIEW'].includes(submission.status)} label="Kirim & tinjau"/><Step index={4} done={submission.status==='APPROVED'} active={submission.status==='REVISION_REQUESTED'} label="Tindak lanjut"/></div><div className="mobile-tabs"><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}>{user.role==='reviewer'?'Peninjauan':'Percakapan'}</button><button className={tab==='documents'?'active':''} onClick={()=>setTab('documents')}>Data & dokumen</button></div><div className={`workspace-grid tab-${tab}`}><div className="left-column">{user.role==='student'?<ChatPanel submission={submission} action={action} busy={!!busy} onNavigate={navigate}/>:<ReviewerView submission={submission} action={action} busy={!!busy}/>}</div><div className="right-column"><SubmissionFields submission={submission} config={config} action={action} busy={!!busy} editable={editable}/>{user.role==='student'&&<RevisionPanel submission={submission} config={config} action={action} busy={!!busy}/>}<DocumentUpload submission={submission} config={config} editable={editable} busy={!!busy} action={action} onChange={setSubmission} onError={report} setBusy={setBusy}/><PreCheckResult submission={submission} action={action} busy={!!busy} editable={editable} onError={report}/>{config.debug&&<details className="debug-panel"><summary>Diagnostik demo lokal</summary><p>Pengajuan #{submission.id} · versi {submission.data_version} · {submission.sop_version}</p><p>{submission.audit_events.length} peristiwa audit tercatat. Tidak ada kredensial atau lokasi penyimpanan ditampilkan.</p></details>}</div></div></>:<div className="reviewer-empty"><FolderOpen size={40}/><h2>Belum ada pengajuan terkirim</h2><p>Pengajuan mahasiswa akan muncul di sini setelah dikirim secara eksplisit.</p></div>}
    </main>}<footer className="app-footer"><span>FlowFix <span>·</span> Administrasi yang lebih jelas.</span><span>Manusia tetap memegang keputusan.</span></footer></div>{sop&&config&&<Modal className="sop-modal" label="Persyaratan pengajuan magang" onClose={()=>setSop(false)}><header><div><p className="eyebrow">PANDUAN DEMO</p><h2 id="sop-title">Persyaratan pengajuan magang</h2></div><button className="icon-button" autoFocus aria-label="Tutup panduan" onClick={()=>setSop(false)}><X size={20}/></button></header><div className="simulation-banner">SOP simulasi {config.sop_version}. Bukan kebijakan resmi UNS/FATISDA. Semua identitas dalam paket uji bersifat fiktif.</div><div className="sop-text">{config.sop}</div></Modal>}</div>;
}
